export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const CLEAR_MOVIE_DETAILS = 'CLEAR_MOVIE_DETAILS';
export const GET_CAROUSEL_BACKDROPS = 'GET_CAROUSEL_BACKDROPS';
